#!/usr/bin/env python3
"""
Generate normalized S-121 Source seed SQL from split CSV blocks.

Inputs (UTF-8 with BOM OK):
  - Source Block - Source_Baru.csv
  - Source Block - sourceOnlineResource.csv
  - Source Block - sourceReference.csv

Outputs (dependency order):
  - seed_source_reference.sql
  - seed_source_online_resource.sql
  - seed_source_normalized.sql

Usage (from repo root):
  python real_db_schema/import_source_normalized.py
  python real_db_schema/import_source_normalized.py --validate-only
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

CSV_SOURCE = SCRIPT_DIR / "Source Block - Source_Baru.csv"
CSV_ONLINE = SCRIPT_DIR / "Source Block - sourceOnlineResource.csv"
CSV_REFERENCE = SCRIPT_DIR / "Source Block - sourceReference.csv"

OUT_REFERENCE = SCRIPT_DIR / "seed_source_reference.sql"
OUT_ONLINE = SCRIPT_DIR / "seed_source_online_resource.sql"
OUT_SOURCE = SCRIPT_DIR / "seed_source_normalized.sql"

DATE_COLUMNS = {
    "sourceAdministrativeDateStamp",
    "sourceAuthoritativeDate",
    "sourceRecordation",
}


def sql_val(val: str | None) -> str:
    if val is None:
        return "NULL"
    s = str(val).strip()
    if not s or s.upper() == "NULL":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_date(val: str | None) -> str:
    if val is None:
        return "NULL"
    s = str(val).strip()
    if not s:
        return "NULL"
    return sql_val(s.replace(":", "-"))


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def validate(
    sources: list[dict[str, str]],
    online: list[dict[str, str]],
    references: list[dict[str, str]],
) -> list[str]:
    errors: list[str] = []
    sor_ids = {r["sourceOnlineResourceID"].strip() for r in online}
    ref_ids = {r["sourceReferenceID"].strip() for r in references}

    if len(sor_ids) != len(online):
        errors.append("Duplicate sourceOnlineResourceID in sourceOnlineResource.csv")

    if len(ref_ids) != len(references):
        errors.append("Duplicate sourceReferenceID in sourceReference.csv")

    sids: set[str] = set()
    for row in sources:
        sid = row.get("sID", "").strip()
        if not sid:
            errors.append("Source row missing sID")
            continue
        if sid in sids:
            errors.append(f"Duplicate sID: {sid}")
        sids.add(sid)

        sor = row.get("sourceOnlineResourceID", "").strip()
        ref = row.get("sourceReferenceID", "").strip()
        if sor not in sor_ids:
            errors.append(f"{sid}: unknown sourceOnlineResourceID {sor!r}")
        if ref not in ref_ids:
            errors.append(f"{sid}: unknown sourceReferenceID {ref!r}")

    for row in online:
        if not row.get("sourceOnlineResourceLinkageURL", "").strip():
            errors.append(
                f"{row.get('sourceOnlineResourceID')}: missing linkage URL (required in S-121)"
            )

    return errors


def write_reference_sql(rows: list[dict[str, str]], out: Path) -> int:
    cols = [
        "sourceReferenceID",
        "responsiblePartyOganizationName",
        "responsiblePartyPositionName",
        "responsiblePartyRole",
        "responsiblePartyContactOnline",
        "responsiblePartyContactPhone",
        "responsiblePartyContactAddressCountry",
        "responsiblePartyContactAddressDeliveryPoint",
        "responsiblePartyContactAddressCity",
        "responsiblePartyContactElectronicMailAddress",
        "responsiblePartyContactAddressAdministrativeArea",
        "responsiblePartyContactAddressPostalCode",
    ]
    with out.open("w", encoding="utf-8") as f:
        f.write("-- S-121 Source::responsibleParty (+ contact/address flattened per REF row)\n")
        f.write("-- Generated by import_source_normalized.py\n\n")
        f.write("CREATE TABLE IF NOT EXISTS source_reference (\n")
        f.write("    sourceReferenceID VARCHAR(50) PRIMARY KEY,\n")
        f.write("    responsiblePartyOganizationName TEXT,\n")
        f.write("    responsiblePartyPositionName TEXT,\n")
        f.write("    responsiblePartyRole VARCHAR(50),\n")
        f.write("    responsiblePartyContactOnline TEXT,\n")
        f.write("    responsiblePartyContactPhone VARCHAR(50),\n")
        f.write("    responsiblePartyContactAddressCountry VARCHAR(100),\n")
        f.write("    responsiblePartyContactAddressDeliveryPoint TEXT,\n")
        f.write("    responsiblePartyContactAddressCity VARCHAR(100),\n")
        f.write("    responsiblePartyContactElectronicMailAddress VARCHAR(255),\n")
        f.write("    responsiblePartyContactAddressAdministrativeArea VARCHAR(100),\n")
        f.write("    responsiblePartyContactAddressPostalCode VARCHAR(50)\n")
        f.write(");\n\n")
        f.write("-- Memasukkan data dari Source Block - sourceReference.csv\n")
        for row in rows:
            vals = [sql_val(row.get(c)) for c in cols]
            f.write(
                f"INSERT INTO source_reference ({', '.join(cols)}) "
                f"VALUES ({', '.join(vals)}) "
                f"ON CONFLICT (sourceReferenceID) DO NOTHING;\n"
            )
    return len(rows)


def write_online_sql(rows: list[dict[str, str]], out: Path) -> int:
    cols = [
        "sourceOnlineResourceID",
        "sourceOnlineResourceLinkageURL",
        "sourceOnlineResourceProtocol",
        "sourceOnlineResourceApplicationProfile",
        "sourceOnlineResourceName",
        "sourceOnlineResourceDescription",
        "sourceOnlineResourceFunction",
    ]
    with out.open("w", encoding="utf-8") as f:
        f.write("-- S-121 Source::onlineResource\n")
        f.write("-- Generated by import_source_normalized.py\n\n")
        f.write("CREATE TABLE IF NOT EXISTS source_online_resource (\n")
        f.write("    sourceOnlineResourceID VARCHAR(50) PRIMARY KEY,\n")
        f.write("    sourceOnlineResourceLinkageURL TEXT NOT NULL,\n")
        f.write("    sourceOnlineResourceProtocol VARCHAR(50),\n")
        f.write("    sourceOnlineResourceApplicationProfile VARCHAR(100),\n")
        f.write("    sourceOnlineResourceName TEXT,\n")
        f.write("    sourceOnlineResourceDescription TEXT,\n")
        f.write("    sourceOnlineResourceFunction VARCHAR(100)\n")
        f.write(");\n\n")
        f.write("-- Memasukkan data dari Source Block - sourceOnlineResource.csv\n")
        for row in rows:
            vals = [sql_val(row.get(c)) for c in cols]
            f.write(
                f"INSERT INTO source_online_resource ({', '.join(cols)}) "
                f"VALUES ({', '.join(vals)}) "
                f"ON CONFLICT (sourceOnlineResourceID) DO NOTHING;\n"
            )
    return len(rows)


def write_source_sql(rows: list[dict[str, str]], out: Path) -> int:
    cols = [
        "sID",
        "sourceDocumentName",
        "sourceRegistryNumber",
        "sourceAdministrativeDateStamp",
        "sourceAuthoritativeDate",
        "sourceDocumentType",
        "sourceAvailabilityStatus",
        "administrativeSourceType",
        "spatialSourceType",
        "sourceType",
        "sourceRecordation",
        "sourceOnlineResourceID",
        "sourceReferenceID",
    ]
    with out.open("w", encoding="utf-8") as f:
        f.write("-- S-121 Source::Source (core attributes + FK to onlineResource & responsibleParty)\n")
        f.write("-- Generated by import_source_normalized.py\n")
        f.write("-- Prasyarat: seed_source_reference.sql, seed_source_online_resource.sql\n\n")
        f.write("CREATE TABLE IF NOT EXISTS source (\n")
        f.write("    sID VARCHAR(50) PRIMARY KEY,\n")
        f.write("    sourceDocumentName TEXT NOT NULL,\n")
        f.write("    sourceRegistryNumber TEXT,\n")
        f.write("    sourceAdministrativeDateStamp DATE,\n")
        f.write("    sourceAuthoritativeDate DATE,\n")
        f.write("    sourceDocumentType VARCHAR(100) NOT NULL,\n")
        f.write("    sourceAvailabilityStatus VARCHAR(50),\n")
        f.write("    administrativeSourceType VARCHAR(50),\n")
        f.write("    spatialSourceType VARCHAR(50),\n")
        f.write("    sourceType VARCHAR(50),\n")
        f.write("    sourceRecordation DATE,\n")
        f.write("    sourceOnlineResourceID VARCHAR(50) NOT NULL,\n")
        f.write("    sourceReferenceID VARCHAR(50) NOT NULL\n")
        f.write(");\n\n")
        f.write("-- Memasukkan data dari Source Block - Source_Baru.csv\n")
        for row in rows:
            vals = []
            for c in cols:
                if c in DATE_COLUMNS:
                    vals.append(sql_date(row.get(c)))
                else:
                    vals.append(sql_val(row.get(c)))
            f.write(
                f"INSERT INTO source ({', '.join(cols)}) "
                f"VALUES ({', '.join(vals)}) "
                f"ON CONFLICT (sID) DO NOTHING;\n"
            )
    return len(rows)


def print_stats(
    sources: list[dict[str, str]],
    online: list[dict[str, str]],
    references: list[dict[str, str]],
) -> None:
    ref_usage: dict[str, int] = {}
    for row in sources:
        rid = row["sourceReferenceID"].strip()
        ref_usage[rid] = ref_usage.get(rid, 0) + 1

    print("--- Analisis normalisasi ---")
    print(f"  source (dokumen)              : {len(sources)} baris")
    print(f"  source_online_resource (SOR)  : {len(online)} baris (1:1 per source)")
    print(f"  source_reference (REF)          : {len(references)} baris unik")
    print("  Pemakaian REF (menghilangkan redundansi):")
    for rid, n in sorted(ref_usage.items()):
        label = next(
            (r["responsiblePartyOganizationName"] for r in references if r["sourceReferenceID"] == rid),
            "?",
        )
        print(f"    {rid}: {n} source(s) -> {label}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate normalized source seed SQL")
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Only validate CSV cross-references; do not write SQL",
    )
    args = parser.parse_args()

    for path in (CSV_SOURCE, CSV_ONLINE, CSV_REFERENCE):
        if not path.is_file():
            print(f"Missing file: {path}", file=sys.stderr)
            return 1

    sources = load_csv(CSV_SOURCE)
    online = load_csv(CSV_ONLINE)
    references = load_csv(CSV_REFERENCE)

    errors = validate(sources, online, references)
    print_stats(sources, online, references)

    if errors:
        print("\nValidation FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    print("\nValidation OK.")

    if args.validate_only:
        return 0

    n_ref = write_reference_sql(references, OUT_REFERENCE)
    n_sor = write_online_sql(online, OUT_ONLINE)
    n_src = write_source_sql(sources, OUT_SOURCE)

    print("\nGenerated:")
    print(f"  {OUT_REFERENCE.name} ({n_ref} rows)")
    print(f"  {OUT_ONLINE.name} ({n_sor} rows)")
    print(f"  {OUT_SOURCE.name} ({n_src} rows)")
    print("\nEksekusi (fresh DB):")
    print("  1. seed_source_reference.sql")
    print("  2. seed_source_online_resource.sql")
    print("  3. seed_source_normalized.sql")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
