-- Membuat tabel relasi rrr_to_bau
CREATE TABLE IF NOT EXISTS rrr_to_bau (
    rrrID VARCHAR(50) NOT NULL,
    uID VARCHAR(50) NOT NULL,
    PRIMARY KEY (rrrID, uID)
);

-- Memasukkan data dari CSV
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-001', 'BA_01') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_01') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_01') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_01') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-001', 'BA_01') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-003', 'BA_02') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_02') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_02') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_02') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-004', 'BA_02') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-002', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-004', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-002', 'BA_03') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-002', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-005', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-004', 'BA_04') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-002', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-005', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-005', 'BA_05') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-001', 'BA_06') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_06') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_06') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_06') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-006', 'BA_06') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-001', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-001', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-002', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-003', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-006', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-007', 'BA_07') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-001', 'BA_08') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-006', 'BA_08') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-008', 'BA_08') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RIGHT-004', 'BA_09') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESPONSIBILITY-004', 'BA_09') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-009', 'BA_09') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-010', 'BA_09') ON CONFLICT (rrrID, uID) DO NOTHING;
INSERT INTO rrr_to_bau (rrrID, uID) VALUES ('RESTRICTION-011', 'BA_09') ON CONFLICT (rrrID, uID) DO NOTHING;
