-- Membuat tabel relasi baunit_to_source
CREATE TABLE IF NOT EXISTS baunit_to_source (
    uID VARCHAR(50) NOT NULL,
    sID VARCHAR(50) NOT NULL,
    PRIMARY KEY (uID, sID)
);

-- Memasukkan data dari CSV
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_01', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_01', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_01', 'UU06_1996') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_02', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_02', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_03', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_03', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_04', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_04', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_05', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_05', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_06', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_06', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_06', 'UU06_1996') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_07', 'UNCLOS1982') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_07', 'UU17_1985') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_07', 'UU06_1996') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_08', 'PP37_2002') ON CONFLICT (uID, sID) DO NOTHING;
INSERT INTO baunit_to_source (uID, sID) VALUES ('BA_09', 'MOU_AUS_1981') ON CONFLICT (uID, sID) DO NOTHING;
