-- S-121 Feature Model::Zone
-- Generated by import_zone_governance.py

CREATE TABLE IF NOT EXISTS feature_model_zone (
    fuID VARCHAR(50) PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    releasibility_type VARCHAR(50) NOT NULL,
    zone_object_type VARCHAR(100) NOT NULL,
    jurisdiction_domain_type_list VARCHAR(100) NOT NULL,
    surface_relation VARCHAR(50) NOT NULL,
    horizontal_datum VARCHAR(50) NOT NULL,
    start_life_span DATE NOT NULL,
    end_life_span DATE
);

-- Memasukkan data dari Feature Model_ ZONE - Zone.csv
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_TS', 'Territorial Sea Indonesia', 'Internal', 'Territorial Sea', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_CZ', 'Contigous Zone Indonesia', 'Internal', 'Contiguous Zone', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_EEZ', 'Exclusive Economic Zone Indonesia', 'Internal', 'Exclusive Economic Zone', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_CS', 'Continental Shelf Indonesia', 'Internal', 'Continental Shelf', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_FISH', 'Fisheries Zone Indonesia', 'Internal', 'Fisheries Zone', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
INSERT INTO feature_model_zone (fuID, label, releasibility_type, zone_object_type, jurisdiction_domain_type_list, surface_relation, horizontal_datum, start_life_span, end_life_span) VALUES ('ZONE_ECS', 'Extentional Continental Shelf Indonesia', 'Internal', 'Continental Shelf', 'Water Surface', 'On Surface', 'WGS84', '2026-04-24', NULL) ON CONFLICT (fuID) DO NOTHING;
