-- Relasi Zone -> Basic Administrative Unit
-- Generated by import_zone_governance.py
-- Prasyarat: seed_zone.sql, seed_baunit.sql

CREATE TABLE IF NOT EXISTS fmzone_to_bau (
    fuid_zone VARCHAR(50) NOT NULL,
    uID VARCHAR(50) NOT NULL,
    PRIMARY KEY (fuid_zone, uID)
);

-- Memasukkan data dari Feature Model_ ZONE - R_ Zone_BAU.csv
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_TS', 'BA_01') ON CONFLICT (fuid_zone, uID) DO NOTHING;
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_CZ', 'BA_02') ON CONFLICT (fuid_zone, uID) DO NOTHING;
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_EEZ', 'BA_03') ON CONFLICT (fuid_zone, uID) DO NOTHING;
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_CS', 'BA_04') ON CONFLICT (fuid_zone, uID) DO NOTHING;
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_FISH', 'BA_09') ON CONFLICT (fuid_zone, uID) DO NOTHING;
INSERT INTO fmzone_to_bau (fuid_zone, uID) VALUES ('ZONE_ECS', 'BA_05') ON CONFLICT (fuid_zone, uID) DO NOTHING;
