-- S-121 Source::responsibleParty (+ contact/address flattened per REF row)
-- Generated by import_source_normalized.py

CREATE TABLE IF NOT EXISTS source_reference (
    sourceReferenceID VARCHAR(50) PRIMARY KEY,
    responsiblePartyOganizationName TEXT,
    responsiblePartyPositionName TEXT,
    responsiblePartyRole VARCHAR(50),
    responsiblePartyContactOnline TEXT,
    responsiblePartyContactPhone VARCHAR(50),
    responsiblePartyContactAddressCountry VARCHAR(100),
    responsiblePartyContactAddressDeliveryPoint TEXT,
    responsiblePartyContactAddressCity VARCHAR(100),
    responsiblePartyContactElectronicMailAddress VARCHAR(255),
    responsiblePartyContactAddressAdministrativeArea VARCHAR(100),
    responsiblePartyContactAddressPostalCode VARCHAR(50)
);

-- Memasukkan data dari Source Block - sourceReference.csv
INSERT INTO source_reference (sourceReferenceID, responsiblePartyOganizationName, responsiblePartyPositionName, responsiblePartyRole, responsiblePartyContactOnline, responsiblePartyContactPhone, responsiblePartyContactAddressCountry, responsiblePartyContactAddressDeliveryPoint, responsiblePartyContactAddressCity, responsiblePartyContactElectronicMailAddress, responsiblePartyContactAddressAdministrativeArea, responsiblePartyContactAddressPostalCode) VALUES ('REF_001', 'United Nations', 'Secretariat / Legal Affairs Division', 'Publisher', 'https://www.un.org/depts/los', '(+1)-212-963-1234', 'International', 'United Nations Headquarters', 'New York', 'doalos@un.org', 'New York', '10017') ON CONFLICT (sourceReferenceID) DO NOTHING;
INSERT INTO source_reference (sourceReferenceID, responsiblePartyOganizationName, responsiblePartyPositionName, responsiblePartyRole, responsiblePartyContactOnline, responsiblePartyContactPhone, responsiblePartyContactAddressCountry, responsiblePartyContactAddressDeliveryPoint, responsiblePartyContactAddressCity, responsiblePartyContactElectronicMailAddress, responsiblePartyContactAddressAdministrativeArea, responsiblePartyContactAddressPostalCode) VALUES ('REF_002', 'Government of the Republic of Indonesia', 'Sekretariat Negara (State Secretariat)', 'Publisher', 'https://peraturan.bpk.go.id/', '(+62)-21-25549000', 'Indonesia', 'Jalan Gatot Subroto, 31', 'Jakarta Pusat', 'eppid@bpk.go.id', 'DKI Jakarta', '10210') ON CONFLICT (sourceReferenceID) DO NOTHING;
INSERT INTO source_reference (sourceReferenceID, responsiblePartyOganizationName, responsiblePartyPositionName, responsiblePartyRole, responsiblePartyContactOnline, responsiblePartyContactPhone, responsiblePartyContactAddressCountry, responsiblePartyContactAddressDeliveryPoint, responsiblePartyContactAddressCity, responsiblePartyContactElectronicMailAddress, responsiblePartyContactAddressAdministrativeArea, responsiblePartyContactAddressPostalCode) VALUES ('REF_003', 'United Nations', 'Secretariat / Legal Affairs Division', 'Custodian', 'https://treaties.un.org', '(+1)-212-963-1234', 'International', '2 UN Plaza - 323 E 44th Street Room DC2-0501', 'New York', 'treatysection@un.org', 'New York', '10017') ON CONFLICT (sourceReferenceID) DO NOTHING;
INSERT INTO source_reference (sourceReferenceID, responsiblePartyOganizationName, responsiblePartyPositionName, responsiblePartyRole, responsiblePartyContactOnline, responsiblePartyContactPhone, responsiblePartyContactAddressCountry, responsiblePartyContactAddressDeliveryPoint, responsiblePartyContactAddressCity, responsiblePartyContactElectronicMailAddress, responsiblePartyContactAddressAdministrativeArea, responsiblePartyContactAddressPostalCode) VALUES ('REF_004', 'Asian Maritime Index', 'Data provider', 'Distributor', 'https://maritimeindex.org', NULL, 'International', 'Maritime Security Lab, Tokyo International University Room 1706, 4-42-31 Higashi-Ikebukuro, Toshima Ward', 'Tokyo', NULL, 'Tokyo', '170-0013') ON CONFLICT (sourceReferenceID) DO NOTHING;
