-- Membuat tabel relasi rrr_to_source
CREATE TABLE IF NOT EXISTS rrr_to_source (
    rrrID VARCHAR(50) NOT NULL,
    sID VARCHAR(50) NOT NULL,
    PRIMARY KEY (rrrID, sID)
);

-- Memasukkan data dari CSV
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-001', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-001', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-001', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-002', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-002', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-003', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-003', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-001', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-001', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-002', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-002', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-003', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-003', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-003', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-003', 'PP36_2002') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-004', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-004', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-005', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-005', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-006', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-006', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-006', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESPONSIBILITY-006', 'PP37_2002') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-001', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-001', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-001', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-002', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-002', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-003', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-003', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-004', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-004', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-005', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-005', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-006', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-006', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-006', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-007', 'UNCLOS1982') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-007', 'UU17_1985') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-007', 'UU06_1996') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-008', 'PP37_2002') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RIGHT-004', 'IDN_AUS_FISHERIES_1993') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-009', 'IDN_AUS_FISHERIES_1993') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-010', 'IDN_AUS_FISHERIES_1993') ON CONFLICT (rrrID, sID) DO NOTHING;
INSERT INTO rrr_to_source (rrrID, sID) VALUES ('RESTRICTION-011', 'IDN_AUS_FISHERIES_1993') ON CONFLICT (rrrID, sID) DO NOTHING;
