-- Relasi Governance -> Basic Administrative Unit
-- Generated by import_zone_governance.py
-- Prasyarat: seed_governance.sql, seed_baunit.sql

CREATE TABLE IF NOT EXISTS governance_to_bau (
    govID VARCHAR(50) NOT NULL,
    uID VARCHAR(50) NOT NULL,
    PRIMARY KEY (govID, uID)
);

-- Memasukkan data dari Governance - Gov_BA.csv
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_01') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_02') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_03') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_04') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_05') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_06') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV001', 'BA_07') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_01') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_02') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_03') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_04') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_05') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_06') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV002', 'BA_07') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV003', 'BA_01') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV003', 'BA_06') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV003', 'BA_07') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV005', 'BA_04') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV006', 'BA_08') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV007', 'BA_09') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_01') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_02') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_03') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_04') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_05') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_06') ON CONFLICT (govID, uID) DO NOTHING;
INSERT INTO governance_to_bau (govID, uID) VALUES ('GOV004', 'BA_07') ON CONFLICT (govID, uID) DO NOTHING;
